### ISSUE TITLE
вопрос по литрам вместо кубов

### ISSUE THREAD

**Issue by xes66** [sergeylysov/sst_cloud#43]
Добрый день!
ранее вы проявляли интерес к данной интеграции
https://github.com/klim123123/neptun_smart_homeassistant

и по ее мотивам 
по счетчику воды нужна ваша помощь
я разобрался как его добавить. Может это конечно и через одно место но у меня заработало.
```
    sensors:
      # Счетчики
      - name: "Slot3 P1 Counter"
        address: 115
        slave: 240
        input_type: holding
        data_type: uint32
        unit_of_measurement: m³
        scale: 0.001
        scan_interval: 10
        device_class: water
        state_class: total_increasing

      - name: "Slot3 P1 Counter Offset"
        address: 115
        slave: 240
        input_type: holding
        data_type: uint32
        scan_interval: 10

      # Для битовых значений в регистре 127
      - name: "Slot3 P1 Status Raw"
        address: 127
        slave: 240
        input_type: holding
        data_type: uint16
        scan_interval: 10

template:
  sensor:  
### Счетчики ####
    - name: "water counter cold"
      state: "{{ states('sensor.slot3_p1_counter') }}"
      unit_of_measurement: m³
      device_class: water
      state_class: total_increasing
```
но он к сожалению считает кубами, то есть надо ждать несколько дней чтоб что то показало))
а раньше было удобно - руки помыл и видишь сколько литров вылил)))
помогите сделать чтоб считал не кубы а литры.
Если знаете как

**Comment by xes66** [comment]
> А само значение как выглядит в кубических метрах, но с определённым количеством знаков после запятой?

Вот так
![Screenshot_20241114_200805_Home Assistant](https://github.com/user-attachments/assets/105c65bb-53a4-471c-90b3-8a7ddbb2ac97)

**Comment by xes66** [comment]
> А как выглядит само значение в кубических метрах, но с определённым количеством знаков после запятой?

И вот тут еще глянул
![Uploading Screenshot_20241114_201345_Home Assistant.jpg…]()

**Comment by klim123123** [comment]
так ведь просто поменять 2 параметра
```
unit_of_measurement: m³
scale: 0.001
```
на
```
unit_of_measurement: L
scale: 1

```

**Comment by sergeylysov** [comment]
а почему два сенсора Slot3 P1 Counter Offset и Slot3 P1 Counter? они чем то отличаются кроме точности? выглядит как будто как раз Slot3 P1 Counter Offset показывает в литрах

**Comment by klim123123** [comment]
Counter Offset это смещение. т.е. если вы подключили счетчик к Нептуну не с 0 значения, вы устанавливаете смещение(начальное значение).

**Comment by klim123123** [comment]
и если будут еще вопросы, пишите в https://github.com/klim123123/neptun_smart_homeassistant
чтобы другие пользователи могли их там найти. потому что наверняка у других будут такие же вопросы.

**Comment by xes66** [comment]
> так ведь просто поменять 2 параметра
> 
> ```
> unit_of_measurement: m³
> scale: 0.001
> ```
> 
> на
> 
> ```
> unit_of_measurement: L
> scale: 1
> ```

я так не стал делать потому что в данном примере который ранее работал на SST было вот так и все работало
не стояло литров но считал их чутьли не онлайн он
```
template:
  - sensor:
    - name: "water counter"
    state: "{{ states('sensor.watercounter') }}"
    unit_of_measurement: m³
    device_class: water
    state_class: total_increasing
```
даже на waterius  работает
![image](https://github.com/user-attachments/assets/daf6cf5e-dc18-4b85-af42-3334f5ced143)

**Comment by xes66** [comment]
> а почему два сенсора Slot3 P1 Counter Offset и Slot3 P1 Counter? они чем то отличаются кроме точности? выглядит как будто как раз Slot3 P1 Counter Offset показывает в литрах


объясняю почему два блока
потому что делал я методом тыка)
вот это добавляет счетчик
```
      - name: "Slot3 P2 Counter"
        address: 117
        slave: 240
        input_type: holding
        data_type: uint32
        unit_of_measurement: m³
        scale: 0.001
        scan_interval: 10
        device_class: water
        state_class: total_increasing
```
его можно добавить как плитку но его нельзя добавить в панель мониторинга энергии
он в таком виде просто не ищется
после добавления второго блока он добавляется
```
template:
  sensor:
    - name: "water counter hot"
      state: "{{ states('sensor.slot3_p2_counter') }}"
      unit_of_measurement: m³
      device_class: water
      state_class: total_increasing  
```
но показывает гребенку не литрами а только когда израсходуется куб
что неудобно и не гибко
хотелось бы сделать чтоб показывал в мониторинге в литрах

**Comment by klim123123** [comment]
теперь понятно чего вы хотели, вы хотели чтобы точность после запятой была выше, а не показания в литрах как вы выразились ранее.

установите `scale: 1`
какие показания у вас получаются?

**Comment by xes66** [comment]
> теперь понятно чего вы хотели, вы хотели чтобы точность после запятой была выше, а не показания в литрах как вы выразились ранее.
> 
> установите `scale: 1` какие показания у вас получаются?

похоже получилось! Спасибо!
сделал для одного счетчика и вот результат
![image](https://github.com/user-attachments/assets/4c7bf514-e8a8-42d4-8580-bcd22baad715)

**Comment by klim123123** [comment]
достаточно цифр? или еще должны быть?
последняя цифра это нули?

**Comment by xes66** [comment]
> достаточно цифр? или еще должны быть? последняя цифра это нуль?

хм
а запятой то нет как на ватериусе
![image](https://github.com/user-attachments/assets/5e5a8082-ded9-4b9f-9c84-04beb840227d)

**Comment by xes66** [comment]
> > достаточно цифр? или еще должны быть? последняя цифра это нуль?
> 
> хм а запятой то нет как на ватериусе ![image](https://private-user-images.githubusercontent.com/31984718/386801140-5e5a8082-ded9-4b9f-9c84-04beb840227d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MTYwMjYsIm5iZiI6MTczMTcxNTcyNiwicGF0aCI6Ii8zMTk4NDcxOC8zODY4MDExNDAtNWU1YTgwODItZGVkOS00YjlmLTljODQtMDRiZWI4NDAyMjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDAwMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NjIwODIyZjA3ZDcwZmQyOGMyMDI3YTdiOWE5MDE5MDVlOTI5OTYwZmI2NGY1MTNhNjkzNzkyZTI0M2VjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OlO0oSmleuvicCE_YXVsnkqmZRRUXWbYASCRUQ1Czc8)

а тут сейчас так
если пробел как запятая обрабатывается то по идее будет норм
но проверить только утром получиться
![image](https://github.com/user-attachments/assets/269954f3-9851-423b-934f-fbcab42e2152)

**Comment by klim123123** [comment]
судя про программе от Нептуна, 310 это уже максимальная точность 
пробел не как запятая, пробел это отделяет тысячи.
если у вас получится 311 и 312 получить, значит он может считать литры.

**Comment by xes66** [comment]
> достаточно цифр? или еще должны быть? последняя цифра это нуль?

тут явно нужна запятая как то но как ее поставить
ну не могли сегодня в душе потратиться 90 000 литров((
![image](https://github.com/user-attachments/assets/64134906-5ee8-42af-82ba-d2d8e94438ef)

**Comment by klim123123** [comment]
запятую поставить не проблема
вы так и не ответили, что у вас меняется при потреблении литра?
после числа 282 310 что было?

**Comment by xes66** [comment]
> Counter Offset это смещение. т.е. если вы подключили счетчик к Нептуну не с 0 значения, вы устанавливаете смещение(начальное значение).

немного не в тему но меня заинтересовал ваш комментарий
у меня есть китайская считалку электроэнергии
но она настолько простая что я не могу задать начальные значения)
и ее показания не такие как на домовом счетчике
![image](https://github.com/user-attachments/assets/4435d761-3c46-4f59-adc6-522d2cc73f43)
скажите можно как то сделать чтоб к этому прибавлялась некая дельта и было как на счетчике от Мосэнергосбыта?

**Comment by xes66** [comment]
> запятую поставить не проблема вы так и не ответили, что у вас меняется при потреблении литра? после числа 282 310 что было?

видимо не понял вопроса
меняется вот так
![image](https://github.com/user-attachments/assets/acf580de-7cb7-4633-89ca-016d880a9409)
то есть сейчас стало уже 282 530

**Comment by klim123123** [comment]
все понял
вам нужно сделать следущее:
```
scale: 0.001
precision: 2
```

жду обратную связь

**Comment by xes66** [comment]
> scale: 0.001
> precision: 2

Спасибо за терпение!
Ого выглядит как хотелось!
понаблюдаю еще за расходом в панели "Энергия"
![image](https://github.com/user-attachments/assets/788db6c9-3890-415e-8d55-9d8fe290fb68)

**Comment by xes66** [comment]
> все понял вам нужно сделать следущее:
> 
> ```
> scale: 0.001
> precision: 2
> ```
> 
> жду обратную связь

сейчас стало совсем шикарно!
![image](https://github.com/user-attachments/assets/9ad0b3a5-084c-463f-830b-d98b6c1db3df)

прошу помочь настроить вывод кВт по счетчику электроэнергии
сейчас показывает вот так
![image](https://github.com/user-attachments/assets/c6f400dd-5188-4d2c-9104-d13ec641a71b)
а мне нужно прибавить к этим показаниям еще пару десятков кВт

**Comment by klim123123** [comment]
> прошу помочь настроить вывод кВт по счетчику электроэнергии
> сейчас показывает вот так
> а мне нужно прибавить к этим показаниям еще пару десятков кВт

откуда берутся данные? скиньте конфиг.

**Comment by xes66** [comment]
> > прошу помочь настроить вывод кВт по счетчику электроэнергии
> > сейчас показывает вот так
> > а мне нужно прибавить к этим показаниям еще пару десятков кВт
> 
> откуда берутся данные? скиньте конфиг.

конфига нет его дает прям сразу m2tt как сенсор
![image](https://github.com/user-attachments/assets/5c9969ac-cc01-4e5b-82ba-bdcfe76793ae)

**Comment by xes66** [comment]
> Helper

спасибо!
я понял что вот так

```
template:
  sensor:
    - name: "entrance-powermeter Электроэнергия"
      state: "{{ (states('sensor.entrance_powermeter_energy') | float) + 17560.88 }}"  #прибаляем разницу
```
скажите а дополнительно нужно прописывать вот это
icon_template: mdi:eye
unit_of_measurement: 'W'
device_class: power
state_class: measurement
